# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetSNP <- function(filename, snpName, chromosome, location, refAllele, altAllele) {
    .Call('_MergeBinaryDosage_GetSNP', PACKAGE = 'MergeBinaryDosage', filename, snpName, chromosome, location, refAllele, altAllele)
}

ReadCreatedFile <- function(filename) {
    invisible(.Call('_MergeBinaryDosage_ReadCreatedFile', PACKAGE = 'MergeBinaryDosage', filename))
}

ReadInterestingStuff <- function(filename) {
    invisible(.Call('_MergeBinaryDosage_ReadInterestingStuff', PACKAGE = 'MergeBinaryDosage', filename))
}

BinaryDosageMerge <- function(mergeFiles, outFilename) {
    .Call('_MergeBinaryDosage_BinaryDosageMerge', PACKAGE = 'MergeBinaryDosage', mergeFiles, outFilename)
}

